name: Publish to PyPI

on:
  release:
    types: [created]

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest

    steps:
      - name: Check out the code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.9"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip

      - name: Build and Publish
        env:
          TWINE_USERNAME: __token__ # PyPI username or use a secret named 'PYPI_USERNAME'
          TWINE_PASSWORD: ${{ secrets.PYPI_TOKEN }} # PyPI token stored as a secret in your repository
        run: |
          python setup.py sdist bdist_wheel
          python -m pip install twine
          twine upload dist/*

